# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zac & Marie's Cookbook
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a curated collection of recipes that Marie and I have found and want to share with others!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://recipes.blanco.io" # the base hostname & protocol for your site
twitter_username: ZacBlanco
github_username:  ZacBlanco

# Build settings
markdown: kramdown
